# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2odAXjMvBoaAC8f3UQw9wFzLWGpAmKp
"""

!pip install streamlit joblib rdkit

import streamlit as st
import joblib
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem

# Load the model
model = joblib.load("random_forest_tgr.pkl")

# Convert SMILES to Morgan fingerprint
def smiles_to_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return np.array(AllChem.GetMorganFingerprintAsBitVect(mol, radius=2, nBits=2048)).reshape(1, -1)
    else:
        return None

# Streamlit UI
st.title("🧪 TGR Activity Predictor")
st.markdown("Enter a compound SMILES to predict if it's **Active** or **Inactive** against TGR.")

user_input = st.text_input("👉 Enter SMILES:", "")

if st.button("Predict"):
    fp = smiles_to_fp(user_input)
    if fp is None:
        st.error("Invalid SMILES string. Please try again.")
    else:
        prediction = model.predict(fp)[0]
        activity = "🟢 Active" if prediction == 1 else "🔴 Inactive"
        st.success(f"Prediction: **{activity}**")

